language: csharp
solution: MovieListApp.sln
install:
  - nuget restore MovieListApp.sln
script:
  - msbuild /p:Configuration=Release MovieListApp.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./MovieListApp.Test/bin/Release/MovieListApp.Test.dll
deploy:
  provider: azure_web_apps
  username: $AZURE_WA_USERNAME
  password: $AZURE_WA_PASSWORD
  site: "YourMovieList"